# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('ospf', ['core', 'internet', 'applications', 'point-to-point', 'mobility', 'internet-apps'])
    module.source = [
        'model/ospf-app.cc',
        'model/ospf-app-config.cc',
        'model/ospf-app-lifecycle.cc',
        'model/ospf-app-io.cc',
        'model/ospf-app-io-component.cc',
        'model/ospf-app-neighbor.cc',
        'model/ospf-app-neighbor-fsm.cc',
        'model/ospf-app-lsa-routing.cc',
            'model/ospf-app-sockets.cc',
        'model/ospf-app-logging.cc',
        'model/ospf-app-rng.cc',
            'model/ospf-app-area-leader-controller.cc',
        'model/ospf-app-routing-engine.cc',
            'model/ospf-app-lsa-processor.cc',
        'model/ospf-app-import-export.cc',
        'model/ospf-app-state-serializer.cc',
        'model/ospf-interface.cc',
        'model/ospf-neighbor.cc',
        'model/packets/ospf-header.cc',
        'model/packets/ospf-hello.cc',
        'model/packets/ls-ack.cc',
        'model/packets/ls-request.cc',
        'model/packets/ls-update.cc',
        'model/packets/ospf-dbd.cc',
        'model/lsa/lsa-header.cc',
        'model/lsa/lsa.cc',
        'model/lsa/router-lsa.cc',
        'model/lsa/l1-summary-lsa.cc',
        'model/lsa/area-lsa.cc',
        'model/lsa/l2-summary-lsa.cc',
        'helper/ospf-app-helper.cc',
        'helper/ospf-packet-helper.cc',
        'helper/ospf-runtime-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ospf')
    module_test.source = [
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
    ])

    headers = bld(features='ns3header')
    headers.module = 'ospf'
    headers.source = [
        'model/ospf-app.h',
        'model/ospf-interface.h',
        'model/ospf-neighbor.h',
        'model/next-hop.h',
        'model/packets/ospf-header.h',
        'model/packets/ospf-hello.h',
        'model/packets/ls-ack.h',
        'model/packets/ls-request.h',
        'model/packets/ls-update.h',
        'model/packets/ospf-dbd.h',
        'model/lsa/lsa-header.h',
        'model/lsa/lsa.h',
        'model/lsa/router-lsa.h',
        'model/lsa/l1-summary-lsa.h',
        'model/lsa/area-lsa.h',
        'model/lsa/l2-summary-lsa.h',
        'helper/ospf-app-helper.h',
        'helper/ospf-packet-helper.h',
        'helper/ospf-runtime-helper.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()

