/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */

#include "ospf-app-lsa-processor.h"

#include "ospf-app-private.h"

namespace ns3 {

namespace {

LsaHeader::LsaKey
MakeLsaKey (const LsaHeader &header)
{
  return std::make_tuple (header.GetType (), header.GetLsId (), header.GetAdvertisingRouter ());
}

template <typename T>
void
IndexLsdb (const std::map<uint32_t, std::pair<LsaHeader, Ptr<T>>> &lsdb,
           std::map<LsaHeader::LsaKey, std::pair<LsaHeader, Ptr<Lsa>>> &indexed)
{
  for (const auto &[id, lsa] : lsdb)
    {
      (void)id;
      indexed.emplace (MakeLsaKey (lsa.first),
                       std::make_pair (lsa.first, StaticCast<Lsa> (lsa.second)));
    }
}

} // namespace

OspfLsaProcessor::OspfLsaProcessor (OspfApp &app)
  : m_app (app)
{
}

void
OspfLsaProcessor::HandleLsr (uint32_t ifIndex, Ipv4Header ipHeader, OspfHeader ospfHeader,
                             Ptr<LsRequest> lsr)
{
  if (ifIndex >= m_app.m_ospfInterfaces.size () || m_app.m_ospfInterfaces[ifIndex] == nullptr)
    {
      NS_LOG_WARN ("LSR dropped due to invalid ifIndex: " << ifIndex);
      return;
    }

  auto interface = m_app.m_ospfInterfaces[ifIndex];
  Ptr<OspfNeighbor> neighbor =
      interface->GetNeighbor (Ipv4Address (ospfHeader.GetRouterId ()), ipHeader.GetSource ());

  if (neighbor == nullptr)
    {
      return;
    }
  if (neighbor->GetState () < OspfNeighbor::Loading)
    {
      NS_LOG_WARN ("Received LSR when the state is not at least Loading");
    }

  std::map<LsaHeader::LsaKey, std::pair<LsaHeader, Ptr<Lsa>>> indexedLsdb;
  IndexLsdb (m_app.m_routerLsdb, indexedLsdb);
  IndexLsdb (m_app.m_l1SummaryLsdb, indexedLsdb);
  IndexLsdb (m_app.m_areaLsdb, indexedLsdb);
  IndexLsdb (m_app.m_l2SummaryLsdb, indexedLsdb);

  std::vector<std::pair<LsaHeader, Ptr<Lsa>>> requestedLsas;
  requestedLsas.reserve (lsr->GetNLsaKeys ());
  for (const auto &lsaKey : lsr->GetLsaKeys ())
    {
      auto it = indexedLsdb.find (lsaKey);
      if (it == indexedLsdb.end ())
        {
          NS_LOG_WARN ("Requested LSA is unavailable for key=" << LsaHeader::GetKeyString (lsaKey));
          continue;
        }
      requestedLsas.emplace_back (it->second);
    }

  if (requestedLsas.empty ())
    {
      NS_LOG_WARN ("No LSAs available to satisfy LSR on interface " << ifIndex);
      return;
    }

  // Construct LS Updates as implicit ACKs based on the received LSR.
  std::vector<Ptr<LsUpdate>> lsUpdates;
  Ptr<LsUpdate> lsUpdate = Create<LsUpdate> ();
  for (const auto &[header, lsa] : requestedLsas)
    {
      if (lsUpdate->GetSerializedSize () + header.GetLength () > interface->GetMtu () - 100 &&
          lsUpdate->GetNLsa () > 0)
        {
          lsUpdates.emplace_back (lsUpdate);
          lsUpdate = Create<LsUpdate> ();
        }
      lsUpdate->AddLsa (header, lsa);
    }
  if (lsUpdate->GetNLsa () > 0)
    {
      lsUpdates.emplace_back (lsUpdate);
    }
  NS_LOG_INFO ("Received LSR (" << lsr->GetNLsaKeys () << ") from interface: " << ifIndex);
  for (auto lsUpdate : lsUpdates)
    {
      Ptr<Packet> packet = lsUpdate->ConstructPacket ();
      EncapsulateOspfPacket (packet, m_app.m_routerId, interface->GetArea (),
                             OspfHeader::OspfType::OspfLSUpdate);
      // Implicit Ack, only send once
      m_app.SendToNeighbor (ifIndex, packet, neighbor);
    }
}

void
OspfLsaProcessor::HandleLsu (uint32_t ifIndex, Ipv4Header ipHeader, OspfHeader ospfHeader,
                             Ptr<LsUpdate> lsu)
{
  auto receivedLsa = lsu->GetLsaList ();
  for (auto &[lsaHeader, lsa] : receivedLsa)
    {
      // Handle LSA and send ACK when appropriate
      HandleLsa (ifIndex, ipHeader, ospfHeader, lsaHeader, lsa);
    }
}

void
OspfLsaProcessor::HandleLsa (uint32_t ifIndex, Ipv4Header ipHeader, OspfHeader ospfHeader,
                             LsaHeader lsaHeader, Ptr<Lsa> lsa)
{
  if (ifIndex >= m_app.m_ospfInterfaces.size () || m_app.m_ospfInterfaces[ifIndex] == nullptr)
    {
      NS_LOG_WARN ("LSA dropped due to invalid ifIndex: " << ifIndex);
      return;
    }

  auto interface = m_app.m_ospfInterfaces[ifIndex];
  Ptr<OspfNeighbor> neighbor =
      interface->GetNeighbor (Ipv4Address (ospfHeader.GetRouterId ()), ipHeader.GetSource ());

  if (neighbor == nullptr)
    {
      NS_LOG_WARN ("LSA dropped due to missing neighbor");
      return;
    }

  uint32_t advertisingRouter = lsaHeader.GetAdvertisingRouter ();
  uint32_t seqNum = lsaHeader.GetSeqNum ();
  LsaHeader::LsaKey lsaKey = lsaHeader.GetKey ();

  // Filter out L2 LSA across the area (only happens in multi-access broadcast)
  if (neighbor->GetArea () != m_app.m_areaId &&
      (lsaHeader.GetType () == LsaHeader::RouterLSAs || lsaHeader.GetType () == LsaHeader::L1SummaryLSAs))
    {
      return;
    }

  auto ackPacket = ConstructLSAckPacket (m_app.m_routerId, m_app.m_areaId, lsaHeader);
  // If the LSA was originally generated by the receiving router, the packet is dropped.
  // Ack is sent
  if (advertisingRouter == m_app.m_routerId.Get ())
    {
      NS_LOG_INFO ("LSU is dropped, received LSU has originated here");
      m_app.SendAck (ifIndex, ackPacket, neighbor->GetIpAddress ());
      return;
    }

  // Initialize local seqNum if it does not exist
  if (m_app.m_seqNumbers.find (lsaKey) == m_app.m_seqNumbers.end ())
    {
      m_app.m_seqNumbers[lsaKey] = 0;
    }

  // Satisfy LSR
  bool isLsrSatisfied = false;
  if (neighbor->GetState () == OspfNeighbor::Loading)
    {
      auto lastLsr = neighbor->GetLastLsrSent ();
      if (lastLsr != nullptr && lastLsr->HasLsaKey (lsaHeader.GetKey ()))
        {
          isLsrSatisfied = true;
          // If LSU is an implicit ACK to LSR
          lastLsr->RemoveLsaKey (lsaHeader.GetKey ());
          if (lastLsr->IsLsaKeyEmpty ())
            {
              m_app.SendNextLsr (ifIndex, neighbor);
            }
        }
    }

  // If the sequence number equals to that of the last packet received from the
  // originating router, the packet is dropped and ACK is sent.
  if (seqNum == m_app.m_seqNumbers[lsaKey])
    {
      if (!isLsrSatisfied)
        {
          m_app.SendAck (ifIndex, ackPacket, neighbor->GetIpAddress ());
        }

      // Remove lsaKey from retx queue
      neighbor->RemoveKeyedTimeout (lsaKey);
      return;
    }
  else if (seqNum > m_app.m_seqNumbers[lsaKey])
    {
      NS_LOG_INFO ("Installing new LSA: " << seqNum << " > " << m_app.m_seqNumbers[lsaKey]);
      // New LSA
      // Process LSA and update its Seq num
      ProcessLsa (lsaHeader, lsa);

      // Remove lsaKey from retx queue
      neighbor->RemoveKeyedTimeout (lsaKey);

      // Flood the network
      Ptr<LsUpdate> lsUpdate = Create<LsUpdate> ();
      lsUpdate->AddLsa (lsaHeader, lsa);
      m_app.FloodLsu (ifIndex, lsUpdate);

      // Send ACK
      if (!isLsrSatisfied)
        {
          m_app.SendAck (ifIndex, ackPacket, neighbor->GetIpAddress ());
        }
      return;
    }
  else if (!isLsrSatisfied)
    {
      // Stale LSA
      NS_LOG_WARN ("Received stale LSA " << seqNum << " < " << m_app.m_seqNumbers[lsaKey]);
      // Just send ACK
      m_app.SendAck (ifIndex, ackPacket, neighbor->GetIpAddress ());
    }
}

void
OspfLsaProcessor::ProcessLsa (LsaHeader lsaHeader, Ptr<Lsa> lsa)
{
  if (m_app.m_enableLsaTimingLog)
    {
      m_app.PrintLsaTiming (lsaHeader.GetSeqNum (), lsaHeader.GetKey (), Simulator::Now ());
    }
  // Update seq num
  m_app.m_seqNumbers[lsaHeader.GetKey ()] = lsaHeader.GetSeqNum ();
  switch (lsaHeader.GetType ())
    {
    case LsaHeader::RouterLSAs:
      ProcessRouterLsa (lsaHeader, DynamicCast<RouterLsa> (lsa));
      break;
    case LsaHeader::L1SummaryLSAs:
      ProcessL1SummaryLsa (lsaHeader, DynamicCast<L1SummaryLsa> (lsa));
      break;
    case LsaHeader::AreaLSAs:
      ProcessAreaLsa (lsaHeader, DynamicCast<AreaLsa> (lsa));
      break;
    case LsaHeader::L2SummaryLSAs:
      ProcessL2SummaryLsa (lsaHeader, DynamicCast<L2SummaryLsa> (lsa));
      break;
    default:
      NS_LOG_WARN ("Received unsupport LSA type in received LS Update");
      break;
    }
}

void
OspfLsaProcessor::ProcessLsa (std::pair<LsaHeader, Ptr<Lsa>> lsa)
{
  ProcessLsa (lsa.first, lsa.second);
}

void
OspfLsaProcessor::HandleLsAck (uint32_t ifIndex, Ipv4Header ipHeader, OspfHeader ospfHeader,
                               Ptr<LsAck> lsAck)
{
  if (ifIndex >= m_app.m_ospfInterfaces.size () || m_app.m_ospfInterfaces[ifIndex] == nullptr)
    {
      NS_LOG_WARN ("LS Ack dropped due to invalid ifIndex: " << ifIndex);
      return;
    }

  auto interface = m_app.m_ospfInterfaces[ifIndex];
  Ptr<OspfNeighbor> neighbor =
      interface->GetNeighbor (Ipv4Address (ospfHeader.GetRouterId ()), ipHeader.GetSource ());
  auto lsaHeaders = lsAck->GetLsaHeaders ();
  if (neighbor == nullptr)
    {
      NS_LOG_WARN ("LS Ack dropped due to missing neighbor ("
                   << Ipv4Address (ospfHeader.GetRouterId ()) << "," << ipHeader.GetSource ()
                   << ")");
      return;
    }

  if (neighbor->GetState () < OspfNeighbor::Exchange)
    {
      NS_LOG_WARN ("LS Ack dropped since the neighbor hasn't started exchange ("
                   << Ipv4Address (ospfHeader.GetRouterId ()) << "," << ipHeader.GetSource ()
                   << ")");
      return;
    }

  for (auto lsaHeader : lsaHeaders)
    {
      // Remove timeout if the stored seq num have been satisfied
      if (lsaHeader.GetSeqNum () <= m_app.m_seqNumbers[lsaHeader.GetKey ()])
        {
          bool isRemoved = neighbor->RemoveKeyedTimeout (lsaHeader.GetKey ());
          if (isRemoved)
            {
              NS_LOG_INFO ("Removed key (advertising router): "
                           << Ipv4Address (lsaHeader.GetAdvertisingRouter ())
                           << " from the retx timer");
            }
          else
            {
              NS_LOG_INFO ("Key: " << Ipv4Address (lsaHeader.GetAdvertisingRouter ())
                                   << " does not exist in the retx timer");
            }
        }
    }
}

} // namespace ns3
