name: build
on:
  push:
    branches: ["main"]
  pull_request:

  permissions:
    contents: read

  jobs:
    build:
      runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

